version: '3.8'

services:
  database:
    image: mongo
    container_name: mongo-2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "5001:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env


  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
volumes:
  mongo-data:
