version: '3.8'

services:
  database:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    image: ghcr.io/${Mr-Maqsood}/three-tier-app-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env


  frontend:
    image: ghcr.io/${Mr-Maqsood}/three-tier-app-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo-data:
