version: '3.8'

services:
  database:
    image: mongo
    container_name: mongo-4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend-4
    ports:
      - "5003:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env


  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend-4
    ports:
      - "3003:3000"
    depends_on:
      - backend
volumes:
  mongo-data:
